(*
 * File: C_to_F.st
 * Copyright (c) 2023 Loupe
 * https://loupe.team
 * 
 * This file is part of ScaleLib, licensed under the MIT License.
 *
 *) 


(********************************************************************)
(* Converts from degrees Celsius to degrees Fahrenheit 				*)
(********************************************************************)


(* DONE and TESTED DFB *)


FUNCTION C_to_F


C_to_F:=  C * 1.8 + 32.0;


END_FUNCTION
