(*
 * File: F_to_C.st
 * Copyright (c) 2023 Loupe
 * https://loupe.team
 * 
 * This file is part of ScaleLib, licensed under the MIT License.
 *
 *) 


(********************************************************************)
(* Converts from degrees Fahrenheit to degrees Celsius 				*)
(********************************************************************)


(* DONE and TESTED DFB *)


FUNCTION F_to_C


F_to_C:=  ( F - 32.0 ) / 1.8;


END_FUNCTION
